[project]
authors = ["Ryan Oates <ryanfullstack@icloud.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community"]
description = "Add a short description here"
name = "workbenchv3"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0,<25"
python = ">=3.12.8,<3.13"
anthropic = ">=0.43.1,<0.44"
pip = ">=24.3.1,<25"
python-dotenv = ">=1.0.1,<2"
